### ISSUE TITLE
doesnt't build on current master

### ISSUE THREAD

**Issue by matu3ba** [natecraddock/zf#36] opened 2023-03-27 22:46 UTC

**Comment by natecraddock** [comment] 2023-03-28 04:28
So this is by design. zf is packaged in 3 package repositories and so I try to track the latest stable version.

But I have been intending to make an unstable/dev branch. I guess this issue is a motivator. I'll close this once I make that branch.

**Comment by natecraddock** [comment] 2023-03-29 04:42
I have added an `unstable` branch that I will try to keep up to date with Zig master.

**Closed by natecraddock** 2023-03-29 04:42 UTC
